<body>
    <h1>Nova poruka</h1>
    <table>
        <tr>
            <td>
                Ime:
            </td>
            <td>
                {{$name}}
            </td>
        </tr>
        <tr>
            <td>
                Predmet:
            </td>
            <td>
                {{$subject}}
            </td>
        </tr>
        <tr>
            <td>
                Šalje:
            </td>
            <td>
                {{$email}}
            </td>
        </tr>
        <tr>
            <td>
                Poruka:
            </td>
            <td>
                {{$text}}
            </td>
        </tr>
    </table>
</body>